server:
  error:
   include-stacktrace: always

spring:
  datasource:
    url: jdbc:mysql://localhost/anime?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: root 
  jpa:
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: false
#    show-sql: true

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE